### ISSUE TITLE
Data model ids are "Number" type instead of "String" type

### ISSUE THREAD

**Issue by atran25** [atran25/carservation.server#6]
Ids can be a mixture of numbers, strings, and symbols such as "K23!5fx" so it's better to have it as a string datatype than a number datatype.

**Comment by cmtnguyen** [comment]
Agree with issue. Most auto generated ids tend to be a mixture of symbols, letters, and numbers.

**Comment by jonathanSeang** [comment]
Since we're using MongoDB, maybe we can reference using _id rather then generating our own. A problem with this though is that reservations collection needs a reference to parkingSpotID, where parkingSpots do not have its own collection in the database. We'd have to either create a collection for it or continue to generate ids for it our self.
